### ISSUE TITLE
code for model pertaining

### ISSUE THREAD

**Issue by justin-566** [mbosc/twf#1]
I'm sorry to disturb you, but if possible, could you provide the code for model pertaining? I'm sorry, but it seems I can't find the relevant code in the file list. Thank you very much for your help.

**Comment by loribonna** [comment]
Hi @justin-566, sure! The code to produce a pre-trained checkpoint on CUB200, TinyImageNet, and TinyImageNetR (resized to 32x32) is in `models/utils/continual_model.py` inside the function `load_initial_checkpoint`. 
By default, the function loads the pre-trained checkpoint we used for the paper from OneDrive but if you want to create a new pre-trained checkpoint you can override the `get_ckpt_remote_url` to make it return a tuple `(None, None)`.
Let me know it this works.

**Comment by justin-566** [comment]
Thanks! According to your method, I've solved the problem and the result was as good as expected.
